spring:
  application:
    name: pwr-report-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 128MB
      max-request-size: 128MB
  datasource:
      username: pwr-report-service
      password: password
      url: jdbc:mysql://localhost:3306/report
  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true
export:
  # Temporary location where the data source for the BIRT report generation can be found.
  xmlFilePath: src\target\datasource.xml
  # Temporary location where the report will be stored during generation (as BIRT needs to render to filesytem)
  wordLocalLocation: src\target\report\reports\%s\word\%s
  # Temporary location where the report will be stored during generation (as BIRT needs to render to fileystem)
  htmlLocalLocation: src\target\report\reports\preview\%s
  # BIRT will need images on the filesystem. Images will be available here.
  imgLocation: src\target\images
  expiration-in-days: 5
server:
  port: 9005
eureka:
  client:
    enabled: false
management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
      base-path: /meta/actuator
---
spring:
  profiles: bootstrapDatabase
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: pwr-report-service
    password: password
    url: jdbc:mysql://localhost:3306/report
  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  profiles: localDevNoEureka
  redis:
    host: localhost
    port: 6379
    database: 1
eureka:
  client:
    enabled: false
pwr-report-service:
  ribbon:
    ReadTimeout: 20000
    ConnectTimeout: 10000
feign:
  hystrix:
    enabled: true # Enables Hystrix Fallback for Feign clients.
---
spring:
  profiles: localDev
  redis:
    host: localhost
    port: 6379
    database: 1
eureka:
  client:
    enabled: true
    service-url:
       defaultZone: http://power02.corp.hbt.de:8761/eureka
pwr-report-service:
  ribbon:
    ReadTimeout: 20000
    ConnectTimeout: 10000
feign:
  hystrix:
    enabled: true # Enables Hystrix Fallback for Feign clients.
